# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(
        clean: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "ios_ci_test")
    upload_to_testflight
  end
end
